server:
  port: 7777


spring:
  application:
    name: reserves
  ##  rabbitmq:
  ##    host: localhost
  ##    port: 5672
  ##    username: guest
  ##    password: guest
  ##    virtual-host: "/"
  ##
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.1.211:8080/realms/parking/protocol/openid-connect/certs
          issuer-uri: http://192.168.1.211:8080/realms/parking




  datasource:
    url: jdbc:postgresql://192.168.1.211:5432/parqueo
    username: usertest
    password: 123456
    driver-class-name: org.postgresql.Driver


eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.211:8714/eureka/


minio:
  url: http://192.168.1.211:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: parking-files


token:
  principal-attribute: preferred_username
  resource-id: parking-backend
  private-key: a5CBxfwtgsNDQpmwvnxcLgOndpcOeHKq


management:
  tracing:
    sampling:
      probability: 1.0


logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
