server:
  port: 7777

spring:
  application:
    name: parqueo-reservas

  datasource:
    url: jdbc:postgresql://localhost:5432/parqueo
    username: usertest
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update


