server:
  port: ${PORT:7777}


spring:
  application:
    name: reserves
  ##  rabbitmq:
  ##    host: localhost
  ##    port: 5672
  ##    username: guest
  ##    password: guest
  ##    virtual-host: "/"
  ##
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_URI:http://192.168.1.212:8080/realms/parking/protocol/openid-connect/certs}
          issuer-uri: ${ISSUER_URI:http://192.168.1.212:8080/realms/parking}




  datasource:
    url: ${BD_URL:jdbc:postgresql://192.168.1.212:5432/parqueo}
    username: ${BD_USER:usertest}
    password: ${BD_PWD:123456}
    driver-class-name: org.postgresql.Driver


eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://192.168.1.212:8714/eureka/}


minio:
  url: ${MINIO_URL:http://192.168.1.212:9000}
  access-key: ${MINIO_USER:minioadmin}
  secret-key: ${MINIO_PWD:minioadmin}
  bucket-name: ${MINIO_BUCKET:parking-files}


token:
  principal-attribute: preferred_username
  resource-id: parking-backend
  private-key: ${KEYCLOAK_TOKEN:RGtdPpFHPwf6Nd8zTiBSjWeBGLOzWubZ}


management:
  tracing:
    sampling:
      probability: 1.0


logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]"
